name: Flutter Web
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: 'any'
          cache: true
      - run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Start Web Release Build
        run: flutter build web --release

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v3
        with:
          name: web-release-develop
          path: ./build/web
